# Site settings
title: Körperimpuls
email: christina.elmer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Körperimpuls: Cranio-Sacral-Therapie, Astrologische Homöopathie,
  Psychosomatische Energetik, Focusing, Reiki
baseurl: '' # '/koerperimpuls/public' # the subpath of your site, e.g. /blog/
url: 'https://koerperimpuls.ch' # the base hostname & protocol for your site
twitter_username: christinaelmer
github_username:  christinaelmer

# Build settings
markdown: kramdown
destination: '../public'
timezone: 'Europe/Zurich'
plugins:
  - 'jekyll-coffeescript'
